### ISSUE TITLE
Understanding native auth

### ISSUE THREAD

**Issue by alexellis** [docker-oxford/registry-pi#1]
Hi,

If we were to strip away all the abstraction introduced by using Ansible, could you explain how the admin vs 'user' works?

I've set up a docker registry completely open as a test, and with native auth, but the native auth model does not allow anonymous users to pull images.

You are adding an admin and non-admin user.. do they both need login passwords and in a workshop or event, would you expect everyone who is doing a 'pull' to login with the 'user' account?

Thanks

**Comment by jonatanblue** [comment]
Authentication is defined in [httpd.conf](https://github.com/docker-oxford/registry-pi/blob/master/roles/auth/templates/httpd.conf.j2), and simply restricts access based on request type. "user" can do GET and HEAD, while "admin" is also allowed to do POST PUT DELETE PATCH via the group "pusher" (defined in `httpd.groups`). The setup is identical in every way to the [authenticating proxy tutorial](https://docs.docker.com/registry/apache/) on Docker's website.

So yes, you need to be authenticated with the server before you can pull, and everyone would have to log in before pulling. With this implementation (using htpasswd) that would make the server slower with the number of users. I don't have a good solution for this at present, although I'm sure someone with more Apache experience would be able to point us in the right direction (contributions welcome!) :)

As a quick workaround to enable pull access for anyone on the network, but restrict push, I first pushed the images as admin with the original config, then removed the requirement to be logged in for GET and HEAD, by commenting out this section in `httpd.conf` and restart the apache container:

```
<Limit GET HEAD>
  Require valid-user
</Limit>
```

The problem then is that no one can log in anymore (since `docker login` is a GET request), so you won't be able to push new images as admin.

**Comment by alexellis** [comment]
Thanks @jonatanblue for the explanation. I have just gone through the instructions in the proxying/apache guide and had a regular and admin (pusher) user. Removing the Limit on GET/HEAD sounds like a reasonable option. It is a shame this can't be done through the registry container without having to have a separate linked apache instance.

I am running a Docker meet-up next week which has 40 people RSVP'd - most of the images are small ~50MB but there are a couple of optional ones (mono) which are 300MB +/-. The wi-fi network is fast at the host's site, but do you think a local registry is necessary?

Would you run an open registry with no security (just valid lets encrypt certs), if it was a closed event? There is a possibility that someone may tamper with the images or delete them.

**Comment by jonatanblue** [comment]
We had a Meetup this week with 20 people, but everyone did their homework and pre-pulled the images, so download bandwidth wasn't a problem. If you can (repeatedly) tell your attendees to pull all images prior to the event, you'll avoid a lot of trouble. Additionally, you may want to make sure that the uplink is fast enough, if you want to be able to push images to Docker Hub.

For running a local registry I'd also make sure that the local network allows inter-host communication (many networks don't for security reasons), and if not bring your my router. I'd definitely put push restrictions on the registry before putting it on the network. It prevents people from pushing poisoned images, or just filling up your hard drive :smile:

**Comment by alexellis** [comment]
@jonatanblue at the moment, I'm just hoping that everyone will have installed Docker Toolbox - I'm sure there will be some who haven't.. I have got a local registry working well on my laptop now and I'll just adjust the DNS entry to whatever the private wifi-lan IP is that I'm allocated on the hosts' network on the night. I don't know whether there is inter-host communication on the wifi lan.. I'll ask.

Thanks for putting these repos together... I've been able to figure out what I needed to do using a combination of this and the docker docs. I'd consider using a PI, but unless I set up hostapd setting the wpa_supplicant config is a pain without a screen.
